import { Inter } from 'next/font/google'
import { Providers } from './provider'
import { Container } from '@chakra-ui/react'
import { Header } from './components/organisms/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='ja'>
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <Container size='md' my='5%'>
                        {children}
                    </Container>
                </Providers>
            </body>
        </html>
    )
}
